platform :ios, '8.0'
#use_frameworks!

install! 'cocoapods', :deterministic_uuids => false


target ‘Demo’ do

    pod "DSZKit",
   :git => "https://github.com/DSZ911226/DSZKit.git",
   :subspecs =>  ['Core','Base', 'Tools'],
   :branch => "master"




end
